version: '3'
services:
  model_client:
    build: Model-Client/
    depends_on:
      - model_server
      - minio
  model_server:
    build: Model-Server/
    ports:
      - "8080:8080"
  minio:
    image: "minio/minio"
    ports:
      - 9000:9000
    command: server /data
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: passpass
