# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_server.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model_server.proto',
  package='model_server',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12model_server.proto\x12\x0cmodel_server\"B\n\x04XRow\x12\n\n\x02\x66\x30\x18\x01 \x01(\x02\x12\n\n\x02\x66\x31\x18\x02 \x01(\x02\x12\n\n\x02\x66\x32\x18\x03 \x01(\x02\x12\n\n\x02\x66\x33\x18\x04 \x01(\x02\x12\n\n\x02\x66\x34\x18\x05 \x01(\x02\"X\n\x12GrpcPredictRequest\x12\x10\n\x08\x43lientId\x18\x01 \x01(\x05\x12\x1d\n\x01X\x18\x02 \x03(\x0b\x32\x12.model_server.XRow\x12\x11\n\tModelName\x18\x03 \x01(\t\"#\n\x13GrpcPredictResponse\x12\x0c\n\x04Prob\x18\x01 \x01(\x02\x32_\n\x0bModelServer\x12P\n\x07predict\x12 .model_server.GrpcPredictRequest\x1a!.model_server.GrpcPredictResponse\"\x00\x62\x06proto3'
)




_XROW = _descriptor.Descriptor(
  name='XRow',
  full_name='model_server.XRow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='f0', full_name='model_server.XRow.f0', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f1', full_name='model_server.XRow.f1', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f2', full_name='model_server.XRow.f2', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f3', full_name='model_server.XRow.f3', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f4', full_name='model_server.XRow.f4', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=102,
)


_GRPCPREDICTREQUEST = _descriptor.Descriptor(
  name='GrpcPredictRequest',
  full_name='model_server.GrpcPredictRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ClientId', full_name='model_server.GrpcPredictRequest.ClientId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='X', full_name='model_server.GrpcPredictRequest.X', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ModelName', full_name='model_server.GrpcPredictRequest.ModelName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=192,
)


_GRPCPREDICTRESPONSE = _descriptor.Descriptor(
  name='GrpcPredictResponse',
  full_name='model_server.GrpcPredictResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Prob', full_name='model_server.GrpcPredictResponse.Prob', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=229,
)

_GRPCPREDICTREQUEST.fields_by_name['X'].message_type = _XROW
DESCRIPTOR.message_types_by_name['XRow'] = _XROW
DESCRIPTOR.message_types_by_name['GrpcPredictRequest'] = _GRPCPREDICTREQUEST
DESCRIPTOR.message_types_by_name['GrpcPredictResponse'] = _GRPCPREDICTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

XRow = _reflection.GeneratedProtocolMessageType('XRow', (_message.Message,), {
  'DESCRIPTOR' : _XROW,
  '__module__' : 'model_server_pb2'
  # @@protoc_insertion_point(class_scope:model_server.XRow)
  })
_sym_db.RegisterMessage(XRow)

GrpcPredictRequest = _reflection.GeneratedProtocolMessageType('GrpcPredictRequest', (_message.Message,), {
  'DESCRIPTOR' : _GRPCPREDICTREQUEST,
  '__module__' : 'model_server_pb2'
  # @@protoc_insertion_point(class_scope:model_server.GrpcPredictRequest)
  })
_sym_db.RegisterMessage(GrpcPredictRequest)

GrpcPredictResponse = _reflection.GeneratedProtocolMessageType('GrpcPredictResponse', (_message.Message,), {
  'DESCRIPTOR' : _GRPCPREDICTRESPONSE,
  '__module__' : 'model_server_pb2'
  # @@protoc_insertion_point(class_scope:model_server.GrpcPredictResponse)
  })
_sym_db.RegisterMessage(GrpcPredictResponse)



_MODELSERVER = _descriptor.ServiceDescriptor(
  name='ModelServer',
  full_name='model_server.ModelServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=231,
  serialized_end=326,
  methods=[
  _descriptor.MethodDescriptor(
    name='predict',
    full_name='model_server.ModelServer.predict',
    index=0,
    containing_service=None,
    input_type=_GRPCPREDICTREQUEST,
    output_type=_GRPCPREDICTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODELSERVER)

DESCRIPTOR.services_by_name['ModelServer'] = _MODELSERVER

# @@protoc_insertion_point(module_scope)
